/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import bcryptjs from 'bcryptjs';
import { DatabaseState, User, Member, Staff, LoanType, Transaction, Inquiry, InquiryReply, Notification, NotificationMetadata, AuditLog, SystemSettings, SmsTemplate, SmsGatewaySettings, PermissionRule, ScheduledBackupConfig, GcashConfig, ReceiptSettings, LandingContent, FinancialPosting, OfficialReceipt, TimeDepositContract, TimeDepositProductConfig, ComplianceConfig } from '../types.js';

const DB_FILE_PATH = path.join(process.cwd(), 'database.json');


const defaultLandingContent: LandingContent = {
  aboutUs: 'A member-owned financial institution built on trust, democratic governance, high annual dividend returns, and accessible credit for community empowerment.',
  mission: 'To empower our members financially through cooperative efforts.',
  vision: 'To be the leading cooperative in the region.',
  services: [
    { title: 'High Dividend Payouts', description: 'Earn annual dividends on share capital plus patronage refunds based on your loan transactions.', icon: 'TrendingUp' },
    { title: 'Lowest Loan Interest Rates', description: 'Access credit facilities with flat-rate interest computation and zero hidden handling surcharges.', icon: 'DollarSign' },
    { title: 'Democratic Governance', description: 'One member, one vote principle. Every member has an equal voice in board elections and policy decisions.', icon: 'Users' },
    { title: 'Mutual Aid & Care Coverage', description: 'Financial assistance during illness, emergency hospitalization, or family bereavement.', icon: 'Shield' }
  ],
  announcements: [
    { id: '1', title: 'General Assembly Meeting', content: 'The annual general assembly will be held next month.', date: new Date().toISOString() }
  ],
  testimonials: [],
  faqs: [
    { question: 'How do I become a member?', answer: 'You can apply online or visit our office with required documents.' },
    { question: 'What are the requirements?', answer: 'Valid ID, proof of income, and initial share capital.' }
  ]
};

const defaultReceiptSettings: ReceiptSettings = {
  orPrefix: 'OR-',
  orNextNumber: 1001,
  numberPadding: 6,
  headerTitle: 'CCT CREDIT COOPERATIVE INC.',
  cdaRegNo: 'CDA-REG-98765-PH',
  tin: '008-123-456-000',
  address: '123 Cooperative Blvd, Quezon City, Metro Manila, Philippines',
  contactPhone: '+1 (555) 019-2834',
  contactEmail: 'cashier@alliancecoop.org',
  logoUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=150&auto=format&fit=crop&q=80',
  footerNote: 'This is an Official Receipt generated by CCT Cooperative Core Financial System. Thank you for building your cooperative equity!',
  authorizedSignatoryName: 'Jane Smith',
  authorizedSignatoryTitle: 'Chief Cashier & Finance Officer'
};

const defaultGcashConfig: GcashConfig = {
  enabled: true,
  accountName: 'CCT COOPERATIVE INC.',
  mobileNumber: '0917-888-2288',
  qrCodeUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="300" viewBox="0 0 300 300"><rect width="300" height="300" fill="%230052cc"/><rect x="18" y="18" width="264" height="264" rx="20" fill="white"/><text x="150" y="52" font-family="sans-serif" font-weight="bold" font-size="20" fill="%230052cc" text-anchor="middle">GCash QR Payment</text><text x="150" y="72" font-family="sans-serif" font-weight="600" font-size="12" fill="%23444444" text-anchor="middle">CCT COOPERATIVE INC.</text><rect x="45" y="85" width="210" height="155" rx="12" fill="%23f0f4ff" stroke="%230052cc" stroke-width="2"/><g fill="%230052cc"><rect x="60" y="100" width="45" height="45"/><rect x="70" y="110" width="25" height="25" fill="white"/><rect x="195" y="100" width="45" height="45"/><rect x="205" y="110" width="25" height="25" fill="white"/><rect x="60" y="180" width="45" height="45"/><rect x="70" y="190" width="25" height="25" fill="white"/><rect x="120" y="100" width="15" height="15"/><rect x="145" y="100" width="15" height="15"/><rect x="165" y="100" width="15" height="15"/><rect x="120" y="125" width="30" height="20"/><rect x="160" y="125" width="20" height="20"/><rect x="115" y="152" width="70" height="20"/><rect x="120" y="180" width="20" height="30"/><rect x="150" y="180" width="35" height="15"/><rect x="195" y="180" width="20" height="35"/><rect x="220" y="195" width="15" height="20"/></g><text x="150" y="262" font-family="monospace" font-weight="bold" font-size="14" fill="%230052cc" text-anchor="middle">0917-888-2288</text><text x="150" y="278" font-family="sans-serif" font-size="10" fill="%23666666" text-anchor="middle">Scan with GCash App</text></svg>',
  instructions: '1. Open GCash app and tap "QR" or "Send Money".\n2. Scan this QR Code or send directly to 0917-888-2288.\n3. Input the exact Amount Due and Payment Reference Number.\n4. Take a screenshot or save the GCash transaction receipt.\n5. Upload the proof of payment file below and enter your 13-digit GCash Reference Number.'
};

const defaultTimeDepositConfig: TimeDepositProductConfig = {
  enabled: true,
  minAmount: 1000,
  maxAmount: 1000000,
  availableTerms: [
    { termMonths: 6, interestRate: 0.055, name: '6 Months (5.5% p.a.)' },
    { termMonths: 12, interestRate: 0.065, name: '1 Year (6.5% p.a.)' },
    { termMonths: 24, interestRate: 0.075, name: '2 Years (7.5% p.a.)' }
  ]
};

const defaultPermissions: PermissionRule[] = [
  { module: 'dashboard', name: 'View Overview Dashboard', description: 'Access executive, staff & member dashboards', admin: true, staff: true, member: true },
  { module: 'analytics', name: 'Descriptive Analytics', description: 'Access financial ratios, member demographic & loan trend analytics', admin: true, staff: true, member: false },
  { module: 'verifications', name: 'Member Approvals & Onboarding', description: 'Review, verify, approve & onboard new membership applications', admin: true, staff: true, member: false },
  { module: 'savings', name: 'Manage Savings & Share Capital', description: 'Deposit, withdraw, and view cashier ledger and savings history', admin: true, staff: true, member: true },
  { module: 'loans_apply', name: 'Apply for Loans', description: 'Submit borrowing applications and compute loan schedule', admin: false, staff: false, member: true },
  { module: 'loans_manage', name: 'Loan Processing & Disbursement', description: 'Review, approve, disburse, and update member loan accounts', admin: true, staff: true, member: false },
  { module: 'dividends', name: 'Dividend Computation & Payout', description: 'Compute, declare, and distribute annual net surplus yields', admin: true, staff: true, member: false },
  { module: 'inquiries', name: 'Member Helpdesk & Inquiries', description: 'Submit and respond to member helpdesk inquiry tickets', admin: true, staff: true, member: true },
  { module: 'user_management', name: 'User & Account Management', description: 'Activate, suspend, reset passwords, and assign user account roles', admin: true, staff: false, member: false },
  { module: 'staff_management', name: 'Staff Supervision & Management', description: 'Supervise, manage, activate, deactivate, and audit operations staff accounts', admin: true, staff: false, member: false },
  { module: 'escalations_review', name: 'Management Review & Escalations', description: 'Supervisory review of rejected documents, loan appeals, and disputed transactions', admin: true, staff: false, member: false },
  { module: 'reports', name: 'Financial & Audit Reports', description: 'Generate & export PDF/CSV operational financial reports', admin: true, staff: true, member: false },
  { module: 'permission_management', name: 'Permission & RBAC Matrix', description: 'Configure system-wide module access and user permission overrides', admin: true, staff: false, member: false },
  { module: 'audit_logs', name: 'System Security Audit Trace', description: 'Inspect system-wide security audit logs and action logs', admin: true, staff: false, member: false },
  { module: 'backup_restore', name: 'Database Backup & Recovery', description: 'Export & restore relational JSON snapshots and backup schedules', admin: true, staff: false, member: false },
  { module: 'sms_gateway', name: 'SMS Reminders & Gateway', description: 'Configure SMS gateway, templates, and dispatch automated due alerts', admin: true, staff: true, member: false },
  { module: 'system_settings', name: 'Global System Parameters', description: 'Update cooperative branding, TIN, and system parameters', admin: true, staff: false, member: false },
  { module: 'gcash_payments', name: 'GCash Payments & Verification', description: 'Manage GCash settings, submit payment proofs, and verify cashier payments', admin: true, staff: true, member: true },
  { module: 'official_receipts', name: 'Official Receipts & Printing', description: 'View, generate, reprint, void, and configure Official Receipts', admin: true, staff: true, member: true },
];

const defaultScheduledBackupConfig: ScheduledBackupConfig = {
  enabled: true,
  frequency: 'DAILY',
  retentionCount: 30,
  lastBackupAt: new Date().toISOString(),
  nextBackupAt: new Date(Date.now() + 86400000).toISOString(),
  autoDownload: false
};

// Default SMS Templates
const defaultSmsTemplates: SmsTemplate[] = [
  {
    id: 'tmpl_loan_7d',
    name: 'Loan Payment Reminder (7 Days)',
    category: 'LOAN_DUE',
    content: 'Dear {{Member Name}}, friendly reminder that your loan {{Loan Number}} payment of ₱{{Amount Due}} is due on {{Due Date}}. Ref: {{Payment Reference}}. Thank you for paying on time!',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  },
  {
    id: 'tmpl_loan_3d',
    name: 'Loan Payment Reminder (3 Days)',
    category: 'LOAN_DUE',
    content: 'Dear {{Member Name}}, your loan {{Loan Number}} amortization of ₱{{Amount Due}} is due in 3 days on {{Due Date}}. Please ensure your savings or payment channel is ready.',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  },
  {
    id: 'tmpl_loan_1d',
    name: 'Loan Payment Reminder (1 Day)',
    category: 'LOAN_DUE',
    content: 'URGENT: Dear {{Member Name}}, your loan {{Loan Number}} payment of ₱{{Amount Due}} is due TOMORROW, {{Due Date}}. Pay early to maintain good standing.',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  },
  {
    id: 'tmpl_loan_0d',
    name: 'Loan Payment Due Today Notice',
    category: 'LOAN_DUE',
    content: 'Dear {{Member Name}}, your loan {{Loan Number}} amortization of ₱{{Amount Due}} is due TODAY, {{Due Date}}. Ref: {{Payment Reference}}. Please settle your balance promptly.',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  },
  {
    id: 'tmpl_loan_overdue',
    name: 'Loan Payment Overdue Alert',
    category: 'LOAN_DUE',
    content: 'OVERDUE NOTICE: Dear {{Member Name}}, your loan {{Loan Number}} payment of ₱{{Amount Due}} was due on {{Due Date}} and is now overdue. Please pay immediately to prevent penalty charges.',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  },
  {
    id: 'tmpl_savings_due',
    name: 'Monthly Regular Savings Deposit Reminder',
    category: 'SAVINGS_DUE',
    content: 'Dear {{Member Name}} (Member #{{Member Number}}), your monthly regular savings deposit of ₱{{Amount Due}} is due on {{Due Date}}. Keep building your equity with CCT Cooperative!',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  },
  {
    id: 'tmpl_share_capital',
    name: 'Share Capital Contribution Call',
    category: 'SHARE_CAPITAL_DUE',
    content: 'Dear {{Member Name}}, your scheduled share capital subscription payment of ₱{{Amount Due}} is due on {{Due Date}}. Strengthening your capital increases your annual dividend share.',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  },
  {
    id: 'tmpl_time_deposit',
    name: 'Time Deposit Maturity Notice',
    category: 'TIME_DEPOSIT_MATURITY',
    content: 'Good news {{Member Name}}! Your Time Deposit placement {{Payment Reference}} of ₱{{Amount Due}} matures on {{Due Date}}. Please visit our branch or contact staff for rollover options.',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  },
  {
    id: 'tmpl_announcement',
    name: 'General Member Broadcast Announcement',
    category: 'BULK_ANNOUNCEMENT',
    content: 'CCT Cooperative Update: Dear {{Member Name}}, please be advised of our upcoming General Assembly and dividend distribution schedule. Thank you for your continued patronship!',
    isDefault: true,
    createdAt: new Date('2026-01-01T08:00:00Z').toISOString()
  }
];

// Default Gateway Settings
const defaultSmsGatewaySettings: SmsGatewaySettings = {
  activeGateway: (process.env.SEMAPHORE_API_KEY ? 'Semaphore' : process.env.VONAGE_API_KEY ? 'Vonage' : 'SystemSimulator') as any,
  semaphoreApiKey: process.env.SEMAPHORE_API_KEY || '',
  semaphoreSenderName: process.env.SEMAPHORE_SENDER_NAME || 'ALLIANCE_COOP',
  vonageApiKey: process.env.VONAGE_API_KEY || '',
  vonageApiSecret: process.env.VONAGE_API_SECRET || '',
  vonageFrom: process.env.VONAGE_FROM || 'AllianceCoop',
  customEndpointUrl: '',
  customApiKey: '',
  autoRemindersEnabled: true,
  scheduleOffsetDays: [7, 3, 1, 0, -1]
};

export const defaultComplianceConfig: ComplianceConfig = {
  requirePmesForLoan: true,
  requireOrientationForLoan: true,
  requireKycForLoan: false,
  allowStaffDirectVerify: true,
  requireAttendanceDate: true,
  requireReferenceNumber: false
};

// Initial clean settings
const defaultSettings: SystemSettings = {
  cooperativeName: 'CCT Cooperative',
  contactEmail: 'support@alliancecoop.org',
  contactPhone: '+1 (555) 019-2834',
  smsNotificationsEnabled: true,
  dividendAllocationRate: 70, // 70% of surplus goes to dividends
  reserveFundRate: 10,
  cetfRate: 10,
  cdfRate: 3,
  optionalFundRate: 7,
  dividendPoolShareRate: 70,
  patronagePoolShareRate: 30,
  cdaRegNo: 'CDA-REG-98765-PH',
  tin: '008-123-456-000',
  address: '123 Cooperative Blvd, Quezon City, Metro Manila, Philippines',
  fiscalYear: '2026',
  dividendRate: 0.08, // 8% dividend rate
  minimumShareCapital: 10000,
  minMembershipTenureMonths: 0,
  complianceConfig: defaultComplianceConfig,
};

const defaultLoanTypes: LoanType[] = [
  { id: 'lt_1', name: 'Regular Loan', interestRate: 0.06, maxDurationMonths: 24, minAmount: 5000, maxAmount: 150000, maxActiveLoansAllowed: 3, cbuPercent: 5, processingFeePercent: 2, requiredDocuments: ['PROMISSORY_NOTE', 'INCOME_PROOF'] },
  { id: 'lt_2', name: 'Emergency Loan', interestRate: 0.02, maxDurationMonths: 12, minAmount: 1000, maxAmount: 30000, maxActiveLoansAllowed: 1, cbuPercent: 2, processingFeePercent: 1, requiredDocuments: ['BRGY_CERT_OR_CALAMITY_PROOF'] },
  { id: 'lt_3', name: 'Share Capital Loan', interestRate: 0.04, maxDurationMonths: 36, minAmount: 10000, maxAmount: 500000, maxActiveLoansAllowed: 1, processingFeePercent: 2, requiredDocuments: ['PROMISSORY_NOTE'] },
  { id: 'lt_4', name: 'Appliance Loan', interestRate: 0.05, maxDurationMonths: 18, minAmount: 5000, maxAmount: 75000, requiredDocuments: ['QUOTATION', 'INCOME_PROOF'] },
  { id: 'lt_5', name: 'Educational Loan', interestRate: 0.03, maxDurationMonths: 12, minAmount: 5000, maxAmount: 50000, requiredDocuments: ['SCHOOL_ASSESSMENT', 'PROMISSORY_NOTE'] },
  { id: 'lt_6', name: 'Salary Loan', interestRate: 0.04, maxDurationMonths: 12, minAmount: 5000, maxAmount: 100000, requiredDocuments: ['PAYSLIP', 'CERTIFICATE_OF_EMPLOYMENT'] },
];

// Seed Helper
function createInitialDatabaseState(): DatabaseState {
  const adminSalt = bcryptjs.genSaltSync(10);
  const staffSalt = bcryptjs.genSaltSync(10);
  const memberSalt = bcryptjs.genSaltSync(10);
  const pendingSalt = bcryptjs.genSaltSync(10);

  const adminHash = bcryptjs.hashSync('admin123', adminSalt);
  const staffHash = bcryptjs.hashSync('staff123', staffSalt);
  const memberHash = bcryptjs.hashSync('member123', memberSalt);
  const pendingHash = bcryptjs.hashSync('pending123', pendingSalt);

  const users: User[] = [
    { id: 'u_admin', email: 'admin@coop.com', passwordHash: adminHash, role: 'ADMIN', createdAt: new Date('2026-01-01T08:00:00Z').toISOString() },
    { id: 'u_staff', email: 'staff@coop.com', passwordHash: staffHash, role: 'STAFF', createdAt: new Date('2026-01-02T09:00:00Z').toISOString() },
    { id: 'u_member1', email: 'member@coop.com', passwordHash: memberHash, role: 'MEMBER', createdAt: new Date('2026-01-03T10:00:00Z').toISOString() },
    { id: 'u_member2', email: 'pending@coop.com', passwordHash: pendingHash, role: 'MEMBER', createdAt: new Date('2026-01-10T14:30:00Z').toISOString() },
  ];

  const members: Member[] = [
    {
      id: 'u_member1',
      email: 'member@coop.com',
      fullName: 'John Doe',
      phone: '+1 (555) 123-4567',
      status: 'ACTIVE',
      initialShareCapitalPaid: true,
      shareCapital: 50000,
      regularSavings: 25000,
      timeDeposits: 100000,
      dividendsEarned: 4500,
      createdAt: new Date('2026-01-03T10:00:00Z').toISOString()
    },
    {
      id: 'u_member2',
      email: 'pending@coop.com',
      fullName: 'Jane Smith',
      phone: '+1 (555) 987-6543',
      status: 'ACTIVE',
      initialShareCapitalPaid: true,
      shareCapital: 10000,
      regularSavings: 0,
      timeDeposits: 0,
      dividendsEarned: 0,
      createdAt: new Date('2026-01-10T14:30:00Z').toISOString(),
      address: '456 Rizal Ave, Sampaloc, Manila',
      birthdate: '1994-08-15',
      gender: 'Female',
      civilStatus: 'Single',
      emergencyContact: 'Robert Smith (+1 555-888-9999)',
      occupation: 'Financial Analyst',
      monthlyIncome: 45000,
      govIdUrl: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="250" viewBox="0 0 400 250"><rect width="400" height="250" rx="16" fill="%230f172a"/><rect x="12" y="12" width="376" height="226" rx="12" fill="%231e293b" stroke="%23334155" stroke-width="2"/><rect x="25" y="25" width="70" height="90" rx="8" fill="%2338bdf8"/><circle cx="60" cy="55" r="18" fill="%23f8fafc"/><path d="M40 95 C40 80, 80 80, 80 95" fill="%23f8fafc"/><text x="110" y="45" font-family="sans-serif" font-weight="bold" font-size="15" fill="%23ffffff">PHILIPPINES NATIONAL ID</text><text x="110" y="65" font-family="sans-serif" font-weight="600" font-size="11" fill="%2338bdf8">GOVERNMENT VERIFIED ID CARD</text><text x="110" y="95" font-family="sans-serif" font-size="10" fill="%2394a3b8">CRN / ID NO.</text><text x="110" y="110" font-family="monospace" font-weight="bold" font-size="13" fill="%23f8fafc">7842-9102-4431-8901</text><text x="25" y="145" font-family="sans-serif" font-size="10" fill="%2394a3b8">NAME</text><text x="25" y="162" font-family="sans-serif" font-weight="bold" font-size="14" fill="%23ffffff">SMITH, JANE MARIE</text><text x="25" y="190" font-family="sans-serif" font-size="10" fill="%2394a3b8">DOB: 1994-08-15</text><text x="180" y="190" font-family="sans-serif" font-size="10" fill="%2338bdf8">VALID GOV IDENTIFICATION</text></svg>`,
      govIdFileName: 'jane_smith_philsys_id.svg',
      selfieUrl: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" rx="16" fill="%230f172a"/><rect x="12" y="12" width="376" height="276" rx="12" fill="%231e293b" stroke="%2338bdf8" stroke-width="2"/><circle cx="200" cy="110" r="45" fill="%2338bdf8"/><path d="M140 210 C140 160, 260 160, 260 210" fill="%2338bdf8"/><rect x="110" y="220" width="180" height="36" rx="8" fill="%230284c7"/><text x="200" y="243" font-family="monospace" font-weight="bold" font-size="11" fill="%23ffffff" text-anchor="middle">VERIFICATION SELFIE</text><text x="200" y="275" font-family="sans-serif" font-size="11" fill="%2338bdf8" text-anchor="middle">Live Identity Match Photo</text></svg>`,
      selfieFileName: 'jane_smith_selfie.svg',
      supportingDocUrl: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" rx="16" fill="%230f172a"/><rect x="12" y="12" width="376" height="276" rx="12" fill="%231e293b" stroke="%2310b981" stroke-width="2"/><text x="200" y="50" font-family="sans-serif" font-weight="bold" font-size="14" fill="%23ffffff" text-anchor="middle">PROOF OF MONTHLY INCOME</text><text x="200" y="80" font-family="monospace" font-size="11" fill="%2310b981" text-anchor="middle">Certificate of Employment & Payslip</text><text x="50" y="130" font-family="sans-serif" font-size="11" fill="%2394a3b8">Employee Name: Jane Marie Smith</text><text x="50" y="160" font-family="sans-serif" font-size="11" fill="%2394a3b8">Position: Financial Analyst</text><text x="50" y="190" font-family="sans-serif" font-size="11" fill="%2394a3b8">Gross Monthly Income: P45,000.00</text><text x="50" y="220" font-family="sans-serif" font-size="11" fill="%2310b981">Employer: Metro Financial Inc.</text></svg>`,
      supportingDocFileName: 'jane_smith_income_proof.svg'
    }
  ];

  const staff: Staff[] = [
    {
      id: 'u_staff',
      email: 'staff@coop.com',
      fullName: 'Alice Johnson',
      phone: '+1 (555) 444-5555',
      status: 'ACTIVE',
      createdAt: new Date('2026-01-02T09:00:00Z').toISOString()
    }
  ];

  const initialInquiries: Inquiry[] = [
    {
      id: 'inq_1',
      memberId: 'u_member1',
      memberName: 'John Doe',
      subject: 'Time Deposit Interest Rate Inquiry',
      message: 'Hello, what is the current rate of return on a 12-month time deposit?',
      status: 'RESOLVED',
      createdAt: new Date('2026-02-01T10:00:00Z').toISOString()
    },
    {
      id: 'inq_2',
      memberId: 'u_member1',
      memberName: 'John Doe',
      subject: 'Loan Restructuring Inquiry',
      message: 'Hello, can I extend my current active loan for another 6 months?',
      status: 'OPEN',
      createdAt: new Date('2026-07-15T15:00:00Z').toISOString()
    }
  ];

  const initialInquiryReplies: InquiryReply[] = [
    {
      id: 'rep_1',
      inquiryId: 'inq_1',
      senderId: 'u_staff',
      senderName: 'Alice Johnson',
      senderRole: 'STAFF',
      message: 'Hi John! Our current 12-month Time Deposit rate is 5.5% per annum, credited at maturity.',
      createdAt: new Date('2026-02-01T14:30:00Z').toISOString()
    }
  ];

  const initialTransactions: Transaction[] = [
    { id: 'tx_1', memberId: 'u_member1', memberName: 'John Doe', type: 'DEPOSIT', amount: 50000, description: 'Initial Share Capital Deposit', processedBy: 'Admin', createdAt: new Date('2026-01-03T10:15:00Z').toISOString() },
    { id: 'tx_2', memberId: 'u_member1', memberName: 'John Doe', type: 'DEPOSIT', amount: 25000, description: 'Regular Savings Deposit', processedBy: 'Admin', createdAt: new Date('2026-01-03T10:20:00Z').toISOString() },
    { id: 'tx_3', memberId: 'u_member1', memberName: 'John Doe', type: 'DEPOSIT', amount: 100000, description: '12-Month Time Deposit', processedBy: 'Admin', createdAt: new Date('2026-01-04T11:00:00Z').toISOString() },
    { id: 'tx_4', memberId: 'u_member2', memberName: 'Jane Smith', type: 'DEPOSIT', amount: 10000, description: 'Initial Share Capital Commitment', processedBy: 'System', createdAt: new Date('2026-01-10T14:30:00Z').toISOString() }
  ];

  const initialAuditLogs: AuditLog[] = [
    { id: 'log_1', userId: 'u_admin', userEmail: 'admin@coop.com', userRole: 'ADMIN', action: 'SYSTEM_INITIALIZATION', details: 'Initial cooperative database seeded successfully.', createdAt: new Date('2026-01-01T08:00:00Z').toISOString() },
    { id: 'log_2', userId: 'u_admin', userEmail: 'admin@coop.com', userRole: 'ADMIN', action: 'CREATE_STAFF_ACCOUNT', details: 'Created staff account for Alice Johnson (staff@coop.com)', createdAt: new Date('2026-01-02T09:10:00Z').toISOString() },
    { id: 'log_3', userId: 'u_member1', userEmail: 'member@coop.com', userRole: 'MEMBER', action: 'ONLINE_MEMBER_REGISTRATION', details: 'Member John Doe registered online and was auto-activated for demo.', createdAt: new Date('2026-01-03T10:00:00Z').toISOString() }
  ];

  return {
    users,
    members,
    staff,
    loanTypes: defaultLoanTypes,
    loanApplications: [],
    loans: [],
    loanPayments: [],
    dividendPeriods: [],
    memberDividends: [],
    transactions: initialTransactions,
    inquiries: initialInquiries,
    inquiryReplies: initialInquiryReplies,
    notifications: [],
    auditLogs: initialAuditLogs,
    systemSettings: defaultSettings,
    smsNotifications: [],
    smsTemplates: defaultSmsTemplates,
    smsGatewaySettings: defaultSmsGatewaySettings,
    withdrawalRequests: [],
  };
}

// Low-level DB Accessors
export class CooperativeDB {
  private static state: DatabaseState | null = null;
  private static lastFileMtimeMs: number = 0;

  public static load(forceReload: boolean = false): DatabaseState {
    if (this.state && !forceReload && fs.existsSync(DB_FILE_PATH)) {
      try {
        const stats = fs.statSync(DB_FILE_PATH);
        if (stats.mtimeMs <= this.lastFileMtimeMs) {
          return this.state;
        }
      } catch {
        return this.state;
      }
    }

    try {
      if (fs.existsSync(DB_FILE_PATH)) {
        try {
          this.lastFileMtimeMs = fs.statSync(DB_FILE_PATH).mtimeMs;
        } catch {}
        const fileContent = fs.readFileSync(DB_FILE_PATH, 'utf-8');
        this.state = JSON.parse(fileContent);
        // Fallback for fields in case schema was updated
        if (this.state) {
          if (!this.state.users) this.state.users = [];
          if (!this.state.members) this.state.members = [];
          if (!this.state.staff) this.state.staff = [];
          if (!this.state.loanTypes) this.state.loanTypes = defaultLoanTypes;
          if (!this.state.loanApplications) this.state.loanApplications = [];
          if (!this.state.loans) this.state.loans = [];
          if (!this.state.loanPayments) this.state.loanPayments = [];
          if (!this.state.dividendPeriods) this.state.dividendPeriods = [];
          if (!this.state.memberDividends) this.state.memberDividends = [];
          if (!this.state.transactions) this.state.transactions = [];
          if (!this.state.inquiries) this.state.inquiries = [];
          if (!this.state.inquiryReplies) this.state.inquiryReplies = [];
          if (!this.state.notifications) this.state.notifications = [];
          if (!this.state.auditLogs) this.state.auditLogs = [];
          if (!this.state.systemSettings) this.state.systemSettings = defaultSettings;
          if (!this.state.smsNotifications) this.state.smsNotifications = [];
          if (!this.state.smsTemplates) this.state.smsTemplates = defaultSmsTemplates;
          if (!this.state.smsGatewaySettings) this.state.smsGatewaySettings = defaultSmsGatewaySettings;
          if (!this.state.memberDocuments) this.state.memberDocuments = [];
          if (!this.state.permissions) this.state.permissions = defaultPermissions;
          if (!this.state.scheduledBackupConfig) this.state.scheduledBackupConfig = defaultScheduledBackupConfig;
          if (!this.state.paymentRequests) this.state.paymentRequests = [];
          if (!this.state.timeDepositContracts) this.state.timeDepositContracts = [];
          if (!this.state.withdrawalRequests) this.state.withdrawalRequests = [];
          if (!this.state.financialPostings) this.state.financialPostings = [];
          if (!this.state.memberPatronageRefunds) this.state.memberPatronageRefunds = [];
          if (!this.state.systemSettings.gcashConfig) this.state.systemSettings.gcashConfig = defaultGcashConfig;
          if (!this.state.systemSettings.timeDepositConfig) this.state.systemSettings.timeDepositConfig = defaultTimeDepositConfig;
          if (!this.state.officialReceipts) this.state.officialReceipts = [];
          if (!this.state.receiptSettings) this.state.receiptSettings = defaultReceiptSettings;
          if (!this.state.systemSettings.complianceConfig) this.state.systemSettings.complianceConfig = defaultComplianceConfig;
          
          if (this.state.systemSettings) {
            if (this.state.systemSettings.statutoryReserveFundRate === undefined && (this.state.systemSettings as any).reserveFundRate === undefined) this.state.systemSettings.statutoryReserveFundRate = 10;
            if (this.state.systemSettings.statutoryCetfRate === undefined && (this.state.systemSettings as any).cetfRate === undefined) this.state.systemSettings.statutoryCetfRate = 10;
            if (this.state.systemSettings.statutoryCdfRate === undefined && (this.state.systemSettings as any).cdfRate === undefined) this.state.systemSettings.statutoryCdfRate = 3;
            if (this.state.systemSettings.statutoryOptionalFundRate === undefined && (this.state.systemSettings as any).optionalFundRate === undefined) this.state.systemSettings.statutoryOptionalFundRate = 7;
            if (this.state.systemSettings.dividendPoolShareRate === undefined) this.state.systemSettings.dividendPoolShareRate = 70;
            if (this.state.systemSettings.patronagePoolShareRate === undefined) this.state.systemSettings.patronagePoolShareRate = 30;

            // Mirror alias fields for bidirectional compatibility
            if ((this.state.systemSettings as any).reserveFundRate === undefined) (this.state.systemSettings as any).reserveFundRate = this.state.systemSettings.statutoryReserveFundRate ?? 10;
            if ((this.state.systemSettings as any).cetfRate === undefined) (this.state.systemSettings as any).cetfRate = this.state.systemSettings.statutoryCetfRate ?? 10;
            if ((this.state.systemSettings as any).cdfRate === undefined) (this.state.systemSettings as any).cdfRate = this.state.systemSettings.statutoryCdfRate ?? 3;
            if ((this.state.systemSettings as any).optionalFundRate === undefined) (this.state.systemSettings as any).optionalFundRate = this.state.systemSettings.statutoryOptionalFundRate ?? 7;
          }

          if (this.state.members) {
            this.state.members.forEach(m => {
              if (m.patronageRefundEarned === undefined) m.patronageRefundEarned = 0;
              if (m.dividendsEarned === undefined) m.dividendsEarned = 0;
            });
          }

          // Recalibrate share capital balances based on actual verified deposit transactions
          this.recalibrateShareCapital(this.state);

          return this.state;
        }
      }
    } catch (e) {
      console.error('Failed to read database file, seeding fresh one:', e);
    }

    // Initialize/Seed database if missing or corrupted
    const freshState = createInitialDatabaseState();
    this.recalibrateShareCapital(freshState);
    this.saveState(freshState);
    this.state = freshState;
    return freshState;
  }

  public static save(state: DatabaseState): void {
    this.state = state;
    this.saveState(state);
  }

  public static recalibrateShareCapital(state?: DatabaseState): void {
    const db = state || this.state;
    if (!db || !db.members) return;

    db.members.forEach((member) => {
      // 1. Process active Financial Postings for this member (exclude VOIDED or REVERSED)
      const activePostings = (db.financialPostings || []).filter(
        p => p.status === 'POSTED' && p.memberId === member.id
      );

      const seenPostingKeys = new Set<string>();
      const accountedTxIds = new Set<string>();
      let postingsTotal = 0;
      let latestOrNo: string | undefined;

      for (const p of activePostings) {
        const dedupeKey = p.ledgerTransactionId || p.id;
        if (!seenPostingKeys.has(dedupeKey)) {
          seenPostingKeys.add(dedupeKey);
          if (p.ledgerTransactionId) {
            accountedTxIds.add(p.ledgerTransactionId);
          }

          if (p.postingType === 'SHARE_CAPITAL') {
            postingsTotal += p.amount;
          } else if (p.postingType === 'DIVIDEND_CREDIT' && (
            p.postingKey.toLowerCase().includes('share') ||
            (p.paymentSource as string) === 'DIVIDEND_DISTRIBUTION_SHARE' ||
            (p as any).destination === 'SHARE_CAPITAL' ||
            (p as any).description?.toLowerCase().includes('share')
          )) {
            postingsTotal += p.amount;
          } else if (p.postingType === 'SHARE_CAPITAL_REFUND') {
            postingsTotal -= p.amount;
          } else if (p.postingType === 'WITHDRAWAL' && (
            p.postingKey.toLowerCase().includes('share') ||
            (p as any).description?.toLowerCase().includes('share') ||
            (p as any).paymentSource?.toLowerCase().includes('share')
          )) {
            postingsTotal -= p.amount;
          }

          if (p.officialReceiptNo) {
            latestOrNo = p.officialReceiptNo;
          }
        }
      }

      // 2. Process Ledger Transactions that are NOT already represented in financial postings and are not VOIDED
      const unpostedTxs = (db.transactions || []).filter(
        tx => tx.memberId === member.id &&
              tx.status !== 'VOIDED' &&
              !accountedTxIds.has(tx.id)
      );

      let unpostedTotal = 0;
      let hasQualifyingTx = false;

      for (const tx of unpostedTxs) {
        const desc = (tx.description || '').toLowerCase();
        const type = (tx.type || '').toUpperCase();

        const isShareCapitalDeposit = (
          (type === 'DEPOSIT' || type === 'SHARE_CAPITAL' || type === 'INITIAL_SHARE' || type === 'SHARE_CAPITAL_SUBSCRIPTION') &&
          (desc.includes('share capital') || desc.includes('initial share') || desc.includes('share subscription'))
        );

        const isLoanCbuRetention = (
          (type === 'DEPOSIT' || type === 'SHARE_CAPITAL') &&
          (desc.includes('cbu') || desc.includes('capital build-up') || desc.includes('capital buildup') || desc.includes('retention'))
        );

        const isDividendCreditToShare = (
          type === 'DIVIDEND_CREDIT' &&
          (desc.includes('share capital') || desc.includes('share equity') || desc.includes('to share capital')) &&
          !desc.includes('regular savings') &&
          !desc.includes('savings')
        );

        const isShareCapitalRefund = (
          (type === 'WITHDRAWAL' || type === 'REFUND' || type === 'SHARE_CAPITAL_REFUND') &&
          (desc.includes('share capital') || desc.includes('cbu') || desc.includes('capital build-up') || desc.includes('capital buildup') || desc.includes('refund'))
        );

        if (isShareCapitalDeposit || isLoanCbuRetention || isDividendCreditToShare) {
          hasQualifyingTx = true;
          unpostedTotal += Math.abs(tx.amount);
          if (tx.officialReceiptNumber && !latestOrNo) {
            latestOrNo = tx.officialReceiptNumber;
          }
        } else if (isShareCapitalRefund || (tx.amount < 0 && (desc.includes('share') || desc.includes('cbu')))) {
          hasQualifyingTx = true;
          unpostedTotal -= Math.abs(tx.amount);
        }
      }

      // If member has neither financial postings nor qualifying ledger transactions, balance is strictly 0
      const totalActivitiesCount = seenPostingKeys.size + (hasQualifyingTx ? 1 : 0);
      if (totalActivitiesCount === 0) {
        member.shareCapital = 0;
        member.initialShareCapitalPaid = false;
        return;
      }

      const calculatedBalance = Math.max(0, Number((postingsTotal + unpostedTotal).toFixed(2)));
      member.shareCapital = calculatedBalance;
      member.initialShareCapitalPaid = calculatedBalance > 0;

      if (latestOrNo && !member.initialShareCapitalOfficialReceiptNo) {
        member.initialShareCapitalOfficialReceiptNo = latestOrNo;
      }
    });
  }

  private static isSaving = false;
  private static pendingSave = false;

  private static sanitizeLargeDataUrls(state: DatabaseState): void {
    if (!state) return;
    const uploadsDir = path.join(process.cwd(), 'uploads');
    const extract = (val?: string, prefix = 'file'): string | undefined => {
      if (!val || typeof val !== 'string' || !val.startsWith('data:')) return val;
      try {
        const match = val.match(/^data:([^;]+);base64,(.+)$/);
        if (!match) return val;
        const mime = match[1];
        const b64 = match[2];
        const ext = mime.includes('pdf') ? 'pdf' : mime.includes('png') ? 'png' : 'jpg';
        const hash = crypto.createHash('md5').update(b64).digest('hex').substring(0, 16);
        const filename = `${prefix}_${hash}.${ext}`;
        if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });
        const filepath = path.join(uploadsDir, filename);
        if (!fs.existsSync(filepath)) {
          fs.writeFileSync(filepath, Buffer.from(b64, 'base64'));
        }
        return `/uploads/${filename}`;
      } catch {
        return val;
      }
    };

    if (state.members) {
      for (const m of state.members) {
        if (m.govIdUrl?.startsWith('data:')) m.govIdUrl = extract(m.govIdUrl, 'govid');
        if (m.selfieUrl?.startsWith('data:')) m.selfieUrl = extract(m.selfieUrl, 'selfie');
        if (m.supportingDocUrl?.startsWith('data:')) m.supportingDocUrl = extract(m.supportingDocUrl, 'supp');
        if (m.initialShareCapitalReceiptUrl?.startsWith('data:')) m.initialShareCapitalReceiptUrl = extract(m.initialShareCapitalReceiptUrl, 'receipt');
      }
    }
    if (state.memberDocuments) {
      for (const d of state.memberDocuments) {
        if (d.fileDataUrl?.startsWith('data:')) d.fileDataUrl = extract(d.fileDataUrl, 'doc');
      }
    }
    if (state.loanApplications) {
      for (const a of state.loanApplications) {
        if (a.documents) {
          for (const doc of a.documents) {
            if (doc.fileDataUrl?.startsWith('data:')) doc.fileDataUrl = extract(doc.fileDataUrl, 'loandoc');
          }
        }
      }
    }
    if (state.paymentRequests) {
      for (const p of state.paymentRequests) {
        if (p.proofAttachmentUrl?.startsWith('data:')) p.proofAttachmentUrl = extract(p.proofAttachmentUrl, 'payproof');
        if ((p as any).proofOfPaymentUrl?.startsWith('data:')) (p as any).proofOfPaymentUrl = extract((p as any).proofOfPaymentUrl, 'payproof');
      }
    }
  }

  private static saveState(state: DatabaseState): void {
    if (this.isSaving) {
      this.pendingSave = true;
      return;
    }
    this.isSaving = true;
    try {
      this.sanitizeLargeDataUrls(state);
      const data = JSON.stringify(state);
      const tmpPath = `${DB_FILE_PATH}.tmp`;
      fs.writeFileSync(tmpPath, data, 'utf-8');
      fs.renameSync(tmpPath, DB_FILE_PATH);
      try {
        this.lastFileMtimeMs = fs.statSync(DB_FILE_PATH).mtimeMs;
      } catch {}
      this.isSaving = false;
      if (this.pendingSave) {
        this.pendingSave = false;
        if (this.state) this.saveState(this.state);
      }
    } catch (e) {
      this.isSaving = false;
      console.error('Failed to serialize database:', e);
    }
  }

  // Helper transaction log helper
  public static logAudit(userId: string, email: string, role: string, action: string, details: string) {
    const db = this.load();
    const log: AuditLog = {
      id: 'log_' + Math.random().toString(36).substring(2, 11),
      userId,
      userEmail: email,
      userRole: role as any,
      action,
      details,
      createdAt: new Date().toISOString()
    };
    db.auditLogs.unshift(log); // newest first
    this.save(db);
  }

  // Notification dispatch hook (e.g. for Email delivery)
  private static onNotificationCreatedHook?: (
    userId: string,
    title: string,
    message: string,
    metadata?: NotificationMetadata
  ) => void | Promise<void>;

  public static setNotificationHook(
    hook:
      | ((
          userId: string,
          title: string,
          message: string,
          metadata?: NotificationMetadata
        ) => void | Promise<void>)
      | undefined
  ) {
    this.onNotificationCreatedHook = hook;
  }

  // Create notifications
  public static createNotification(
    userId: string,
    title: string,
    message: string,
    metadata?: NotificationMetadata
  ): Notification {
    const db = this.load();
    const notif: Notification = {
      id: 'ntf_' + Math.random().toString(36).substring(2, 11),
      userId,
      title,
      message,
      isRead: false,
      createdAt: new Date().toISOString(),
      metadata
    };
    db.notifications.unshift(notif);
    this.save(db);

    if (this.onNotificationCreatedHook) {
      try {
        const hookRes = this.onNotificationCreatedHook(userId, title, message, metadata);
        if (hookRes && typeof (hookRes as any).catch === 'function') {
          (hookRes as any).catch((err: any) => {
            console.warn('[DB] Notification hook async error:', err);
          });
        }
      } catch (err) {
        console.warn('[DB] Notification hook error:', err);
      }
    }

    return notif;
  }

  // Centralized Financial Posting Engine with Idempotency & Unique Identity Protection
  public static postFinancialTransaction(params: {
    postingKeys: string[];
    paymentSource: 'INITIAL_SHARE_QUEUE' | 'GCASH_QUEUE' | 'CASHIER_QUEUE' | 'LOAN_DISBURSEMENT' | 'LOAN_PAYMENT_VERIFICATION' | 'DIVIDEND_DISTRIBUTION' | 'PATRONAGE_DISTRIBUTION' | 'SAVINGS_TRANSACTION' | 'OTC_LOAN_PAYMENT' | 'TIME_DEPOSIT_TRANSACTION' | 'PAYMENT_REQUEST_QUEUE';
    memberId: string;
    memberName: string;
    amount: number;
    postingType: 'SHARE_CAPITAL' | 'REGULAR_SAVINGS' | 'LOAN_PAYMENT' | 'LOAN_RELEASE' | 'WITHDRAWAL' | 'DIVIDEND_CREDIT' | 'PATRONAGE_REFUND' | 'TIME_DEPOSIT' | 'SHARE_CAPITAL_REFUND';
    postedBy: string;
    gcashRefNumber?: string;
    executePosting: (db: DatabaseState) => {
      ledgerTransaction: Transaction;
      officialReceipt?: OfficialReceipt;
      additionalData?: any;
    };
  }): {
    success: boolean;
    isAlreadyProcessed?: boolean;
    existingPosting?: FinancialPosting;
    posting?: FinancialPosting;
    ledgerTransaction?: Transaction;
    officialReceipt?: OfficialReceipt;
    additionalData?: any;
    message?: string;
  } {
    const db = this.load();
    db.financialPostings = db.financialPostings || [];

    // Clean, normalize, and validate posting keys
    const cleanKeys = params.postingKeys
      .map(k => (k || '').trim().toLowerCase().replace(/[^a-z0-9_:-]/g, ''))
      .filter(k => k.length >= 3);

    if (cleanKeys.length === 0) {
      return {
        success: false,
        message: 'INVALID_POSTING_KEY: A valid, normalized posting identity key is required for financial posting.'
      };
    }

    const existing = db.financialPostings.find(p => 
      p.status === 'POSTED' && cleanKeys.includes(p.postingKey.toLowerCase())
    );

    if (existing) {
      return {
        success: false,
        isAlreadyProcessed: true,
        existingPosting: existing,
        message: `ALREADY_PROCESSED: This financial payment has already been posted (Posting ID: ${existing.id}, Key: ${existing.postingKey}, OR: ${existing.officialReceiptNo || 'N/A'}).`
      };
    }

    // Execute the balance change and transaction creation
    const { ledgerTransaction, officialReceipt, additionalData } = params.executePosting(db);

    const now = new Date().toISOString();
    const primaryPostingKey = cleanKeys[0] || ('KEY_' + Date.now());

    // Record a posting entry for every alias key so all queues converge to the same posting
    const newPostings: FinancialPosting[] = cleanKeys.map(key => ({
      id: 'post_' + Math.random().toString(36).substring(2, 11),
      postingKey: key,
      paymentSource: params.paymentSource,
      memberId: params.memberId,
      memberName: params.memberName,
      amount: params.amount,
      postingType: params.postingType,
      ledgerTransactionId: ledgerTransaction.id,
      officialReceiptNo: officialReceipt?.receiptNumber,
      postedBy: params.postedBy,
      postedAt: now,
      status: 'POSTED',
      gcashRefNumber: params.gcashRefNumber
    }));

    db.financialPostings.push(...newPostings);
    this.save(db);

    return {
      success: true,
      posting: newPostings[0],
      ledgerTransaction,
      officialReceipt,
      additionalData
    };
  }
}
