import React, { useState, useEffect } from 'react';
import { OfficialReceipt, ReceiptSettings, Role, Member, Loan } from '../types';
import { OfficialReceiptModal } from './OfficialReceiptModal';
import {
  FileText,
  Search,

  PlusCircle,
  Settings,
  Printer,
  XCircle,
  CheckCircle2,

  History,

  RefreshCw,

  DollarSign,
  AlertCircle,
  FileCheck,


} from 'lucide-react';

interface OfficialReceiptModuleProps {
  userRole: Role;
  currentUserId: string;
}

export const OfficialReceiptModule: React.FC<OfficialReceiptModuleProps> = ({
  userRole,

}) => {
  const [receipts, setReceipts] = useState<OfficialReceipt[]>([]);
  const [settings, setSettings] = useState<ReceiptSettings | null>(null);
  const [members, setMembers] = useState<Member[]>([]);
  const [loans, setLoans] = useState<Loan[]>([]);
  const [printLogs, setPrintLogs] = useState<any[]>([]);

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  // Search & Filter state
  const [searchTerm, setSearchTerm] = useState('');
  const [paymentTypeFilter, setPaymentTypeFilter] = useState('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [paymentMethodFilter, setPaymentMethodFilter] = useState('ALL');

  // Selected receipt for modal
  const [selectedReceipt, setSelectedReceipt] = useState<OfficialReceipt | null>(null);

  // Modals state
  const [showIssueModal, setShowIssueModal] = useState(false);
  const [showSettingsModal, setShowSettingsModal] = useState(false);
  const [showLogsModal, setShowLogsModal] = useState(false);

  // Manual Receipt Form
  const [manualForm, setManualForm] = useState({
    memberId: '',
    paymentType: 'SAVINGS_DEPOSIT' as OfficialReceipt['paymentType'],
    paymentMethod: 'CASH' as OfficialReceipt['paymentMethod'],
    amountPaid: '',
    paymentDate: new Date().toISOString().split('T')[0],
    loanId: '',
    paymentReference: '',
    principalAmount: '',
    interestAmount: '',
    penaltyAmount: '',
    feeAmount: '',
    remarks: ''
  });
  const [isSubmittingManual, setIsSubmittingManual] = useState(false);

  // Settings Form
  const [settingsForm, setSettingsForm] = useState<ReceiptSettings>({
    orPrefix: 'OR-',
    orNextNumber: 1001,
    numberPadding: 6,
    headerTitle: 'CCT CREDIT COOPERATIVE INC.',
    cdaRegNo: 'CDA-REG-98765-PH',
    tin: '008-123-456-000',
    address: '123 Cooperative Blvd, Quezon City, Metro Manila, Philippines',
    contactPhone: '+1 (555) 019-2834',
    contactEmail: 'cashier@alliancecoop.org',
    logoUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=150&auto=format&fit=crop&q=80',
    footerNote: 'This is an Official Receipt generated by CCT Cooperative Core Financial System. Thank you for building your cooperative equity!',
    authorizedSignatoryName: 'Jane Smith',
    authorizedSignatoryTitle: 'Chief Cashier & Finance Officer'
  });
  const [isSavingSettings, setIsSavingSettings] = useState(false);

  // Fetch initial data
  const fetchData = async () => {
    setLoading(true);
    setError('');
    try {
      const token = localStorage.getItem('token');
      const headers = {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`
      };

      // Fetch config & receipts in parallel
      const [configRes, receiptsRes] = await Promise.all([
        fetch('/api/receipts/config', { headers }),
        fetch('/api/receipts', { headers })
      ]);

      if (configRes.ok) {
        const configData = await configRes.json();
        setSettings(configData);
        setSettingsForm(configData);
      }

      if (receiptsRes.ok) {
        const receiptsData = await receiptsRes.json();
        setReceipts(receiptsData);
      }

      // If Staff or Admin, load members and loans for manual issuance
      if (userRole === 'ADMIN' || userRole === 'STAFF') {
        const [membersRes, loansRes] = await Promise.all([
          fetch('/api/members', { headers }),
          fetch('/api/loans/active', { headers })
        ]);

        if (membersRes.ok) {
          const mData = await membersRes.json();
          setMembers(mData);
        }

        if (loansRes.ok) {
          const lData = await loansRes.json();
          setLoans(lData);
        }
      }

      if (userRole === 'ADMIN') {
        const logsRes = await fetch('/api/receipts/history/print-logs', { headers });
        if (logsRes.ok) {
          const logsData = await logsRes.json();
          setPrintLogs(logsData);
        }
      }
    } catch (err: any) {
      setError(err.message || 'Failed to load Official Receipts data.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  // Filtered Receipts
  const filteredReceipts = receipts.filter(r => {
    const matchesSearch =
      r.receiptNumber.toLowerCase().includes(searchTerm.toLowerCase().trim()) ||
      r.memberName.toLowerCase().includes(searchTerm.toLowerCase().trim()) ||
      (r.memberNumber && r.memberNumber.toLowerCase().includes(searchTerm.toLowerCase().trim())) ||
      (r.loanNumber && r.loanNumber.toLowerCase().includes(searchTerm.toLowerCase().trim())) ||
      (r.paymentReference && r.paymentReference.toLowerCase().includes(searchTerm.toLowerCase().trim())) ||
      r.paymentDate.includes(searchTerm.trim());

    const matchesType = paymentTypeFilter === 'ALL' || r.paymentType === paymentTypeFilter;
    const matchesStatus = statusFilter === 'ALL' || r.status === statusFilter;
    const matchesMethod = paymentMethodFilter === 'ALL' || r.paymentMethod === paymentMethodFilter;

    return matchesSearch && matchesType && matchesStatus && matchesMethod;
  });

  // Calculate Metrics
  const totalIssuedCount = receipts.filter(r => r.status === 'ISSUED').length;
  const totalVoidedCount = receipts.filter(r => r.status === 'VOIDED').length;
  const totalCollections = receipts
    .filter(r => r.status === 'ISSUED')
    .reduce((sum, r) => sum + r.amountPaid, 0);

  // Handle Manual Receipt Submit
  const handleIssueManualSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!manualForm.memberId || !manualForm.amountPaid || Number(manualForm.amountPaid) <= 0) {
      setError('Please select a member and enter a valid payment amount.');
      return;
    }

    setIsSubmittingManual(true);
    setError('');
    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/receipts/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          memberId: manualForm.memberId,
          paymentType: manualForm.paymentType,
          paymentMethod: manualForm.paymentMethod,
          amountPaid: Number(manualForm.amountPaid),
          paymentDate: manualForm.paymentDate,
          loanId: manualForm.loanId || undefined,
          paymentReference: manualForm.paymentReference || undefined,
          principalAmount: manualForm.principalAmount ? Number(manualForm.principalAmount) : undefined,
          interestAmount: manualForm.interestAmount ? Number(manualForm.interestAmount) : undefined,
          penaltyAmount: manualForm.penaltyAmount ? Number(manualForm.penaltyAmount) : undefined,
          feeAmount: manualForm.feeAmount ? Number(manualForm.feeAmount) : undefined,
          remarks: manualForm.remarks
        })
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to issue Official Receipt.');

      setSuccessMsg(`Official Receipt ${data.receipt.receiptNumber} issued successfully!`);
      setShowIssueModal(false);
      setSelectedReceipt(data.receipt);
      fetchData();
    } catch (err: any) {
      setError(err.message || 'Error creating official receipt.');
    } finally {
      setIsSubmittingManual(false);
    }
  };

  // Handle Settings Save
  const handleSaveSettings = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSavingSettings(true);
    setError('');
    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/receipts/config', {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(settingsForm)
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to update receipt config.');

      setSettings(data.settings);
      setSuccessMsg('Official Receipt numbering format and template updated!');
      setShowSettingsModal(false);
    } catch (err: any) {
      setError(err.message || 'Failed to save settings.');
    } finally {
      setIsSavingSettings(false);
    }
  };

  // Record Print API call
  const recordPrint = async (receiptId: string, action: 'INITIAL_PRINT' | 'REPRINT' | 'PDF_DOWNLOAD') => {
    try {
      const token = localStorage.getItem('token');
      await fetch(`/api/receipts/${receiptId}/print`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({ action })
      });
      fetchData();
    } catch (err) {
      console.error('Failed to log print action:', err);
    }
  };

  // Void Receipt API call
  const handleVoidReceipt = async (receiptId: string, voidReason: string) => {
    const token = localStorage.getItem('token');
    const res = await fetch(`/api/receipts/${receiptId}/void`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`
      },
      body: JSON.stringify({ voidReason })
    });

    const data = await res.json();
    if (!res.ok) throw new Error(data.error || 'Failed to void receipt.');

    setSuccessMsg(`Receipt ${data.receipt.receiptNumber} has been VOIDED.`);
    if (selectedReceipt && selectedReceipt.id === receiptId) {
      setSelectedReceipt(data.receipt);
    }
    fetchData();
  };

  return (
    <div className="space-y-6">
      
      {/* Module Title Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-7 h-7 text-emerald-600" />
            <h1 className="text-2xl font-black text-slate-900 tracking-tight">Official Receipt Module</h1>
          </div>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">
            {userRole === 'MEMBER'
              ? 'View, verify, print, and download your official transaction receipts.'
              : 'Auto-generate, preview, issue, print, and manage official transaction receipts.'}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={fetchData}
            className="p-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-600 transition"
            title="Refresh List"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>

          {(userRole === 'ADMIN' || userRole === 'STAFF') && (
            <button
              onClick={() => {
                setManualForm({
                  memberId: members.length > 0 ? members[0].id : '',
                  paymentType: 'SAVINGS_DEPOSIT',
                  paymentMethod: 'CASH',
                  amountPaid: '',
                  paymentDate: new Date().toISOString().split('T')[0],
                  loanId: '',
                  paymentReference: '',
                  principalAmount: '',
                  interestAmount: '',
                  penaltyAmount: '',
                  feeAmount: '',
                  remarks: ''
                });
                setShowIssueModal(true);
              }}
              className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow-sm transition"
            >
              <PlusCircle className="w-4 h-4" />
              <span>Issue Manual OR</span>
            </button>
          )}

          {userRole === 'ADMIN' && (
            <>
              <button
                onClick={() => setShowLogsModal(true)}
                className="inline-flex items-center gap-1.5 px-3.5 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold text-xs transition"
              >
                <History className="w-4 h-4 text-emerald-600" />
                <span>Print Audit Logs</span>
              </button>

              <button
                onClick={() => setShowSettingsModal(true)}
                className="inline-flex items-center gap-1.5 px-3.5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-semibold text-xs shadow-sm transition"
              >
                <Settings className="w-4 h-4 text-emerald-400" />
                <span>OR Settings</span>
              </button>
            </>
          )}
        </div>
      </div>

      {/* Alert Messages */}
      {error && (
        <div className="p-4 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-medium flex items-center justify-between">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-rose-600 shrink-0" />
            <span>{error}</span>
          </div>
          <button onClick={() => setError('')} className="text-rose-500 hover:text-rose-800 font-bold">×</button>
        </div>
      )}

      {successMsg && (
        <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-medium flex items-center justify-between">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>{successMsg}</span>
          </div>
          <button onClick={() => setSuccessMsg('')} className="text-emerald-500 hover:text-emerald-800 font-bold">×</button>
        </div>
      )}

      {/* Metrics Bar */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-emerald-100 text-emerald-800 rounded-xl">
            <FileCheck className="w-6 h-6" />
          </div>
          <div>
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Issued Receipts</p>
            <p className="text-2xl font-black text-slate-900 mt-0.5">{totalIssuedCount}</p>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-indigo-100 text-emerald-600 rounded-xl">
            <DollarSign className="w-6 h-6" />
          </div>
          <div>
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Total Collections</p>
            <p className="text-xl sm:text-2xl font-black text-slate-900 mt-0.5">
              ₱{totalCollections.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </p>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-rose-100 text-rose-800 rounded-xl">
            <XCircle className="w-6 h-6" />
          </div>
          <div>
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Voided Receipts</p>
            <p className="text-2xl font-black text-slate-900 mt-0.5">{totalVoidedCount}</p>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-amber-100 text-amber-800 rounded-xl">
            <Printer className="w-6 h-6" />
          </div>
          <div>
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">OR Next Counter</p>
            <p className="text-2xl font-mono font-black text-slate-900 mt-0.5">
              {settings ? `${settings.orPrefix}${String(settings.orNextNumber).padStart(settings.numberPadding, '0')}` : 'OR-001001'}
            </p>
          </div>
        </div>
      </div>

      {/* Search & Filter Toolbar */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm space-y-3">
        <div className="flex flex-col md:flex-row items-center gap-3">
          
          {/* Search Input */}
          <div className="relative flex-1 w-full">
            <Search className="w-4 h-4 absolute left-3.5 top-3 text-slate-400" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search by Receipt #, Member Name, Member #, Loan #, Date..."
              className="w-full pl-10 pr-4 py-2 rounded-xl border border-slate-200 text-xs sm:text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
            />
          </div>

          {/* Payment Type Filter */}
          <select
            value={paymentTypeFilter}
            onChange={(e) => setPaymentTypeFilter(e.target.value)}
            className="w-full md:w-auto px-3 py-2 rounded-xl border border-slate-200 text-xs font-medium text-slate-700 bg-white focus:outline-none focus:ring-2 focus:ring-emerald-500"
          >
            <option value="ALL">All Payment Types</option>
            <option value="LOAN_PAYMENT">Loan Repayments</option>
            <option value="SAVINGS_DEPOSIT">Regular Savings</option>
            <option value="SHARE_CAPITAL">Share Capital</option>
            <option value="TIME_DEPOSIT">Time Deposits</option>
            <option value="FEE">Fees</option>
          </select>

          {/* Status Filter */}
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="w-full md:w-auto px-3 py-2 rounded-xl border border-slate-200 text-xs font-medium text-slate-700 bg-white focus:outline-none focus:ring-2 focus:ring-emerald-500"
          >
            <option value="ALL">All Statuses</option>
            <option value="ISSUED">Issued</option>
            <option value="VOIDED">Voided</option>
          </select>

          {/* Payment Method Filter */}
          <select
            value={paymentMethodFilter}
            onChange={(e) => setPaymentMethodFilter(e.target.value)}
            className="w-full md:w-auto px-3 py-2 rounded-xl border border-slate-200 text-xs font-medium text-slate-700 bg-white focus:outline-none focus:ring-2 focus:ring-emerald-500"
          >
            <option value="ALL">All Methods</option>
            <option value="CASH">Cash</option>
            <option value="GCASH">GCash</option>
            <option value="BANK_TRANSFER">Bank Deposit</option>
            <option value="CHECK">Check</option>
          </select>
        </div>
      </div>

      {/* Receipts Table */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        {loading ? (
          <div className="p-12 text-center text-slate-500 text-sm">
            <RefreshCw className="w-6 h-6 animate-spin mx-auto text-emerald-600 mb-2" />
            Loading Official Receipts records...
          </div>
        ) : filteredReceipts.length === 0 ? (
          <div className="p-12 text-center space-y-2">
            <FileText className="w-10 h-10 text-slate-300 mx-auto" />
            <h3 className="text-base font-bold text-slate-800">No Official Receipts Found</h3>
            <p className="text-xs text-slate-500">
              {searchTerm || paymentTypeFilter !== 'ALL' || statusFilter !== 'ALL'
                ? 'Try adjusting your search query or filters.'
                : 'No official receipts have been issued yet. Receipts are generated automatically upon approved payment.'}
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs sm:text-sm">
              <thead className="bg-slate-900 text-white uppercase text-[11px] tracking-wider font-semibold">
                <tr>
                  <th className="py-3 px-4">OR Number</th>
                  <th className="py-3 px-4">Member Name</th>
                  <th className="py-3 px-4">Payment Type</th>
                  <th className="py-3 px-4">Method</th>
                  <th className="py-3 px-4 text-right">Amount Paid</th>
                  <th className="py-3 px-4">Date</th>
                  <th className="py-3 px-4 text-center">Status</th>
                  <th className="py-3 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {filteredReceipts.map((r) => (
                  <tr key={r.id} className="hover:bg-slate-50 transition">
                    <td className="py-3.5 px-4 font-mono font-black text-slate-900">
                      {r.receiptNumber}
                      {r.reprintCount > 0 && (
                        <span className="ml-1.5 px-1.5 py-0.2 rounded bg-amber-100 text-amber-800 text-[9px] font-sans font-bold">
                          Reprint x{r.reprintCount}
                        </span>
                      )}
                    </td>
                    <td className="py-3.5 px-4 font-medium text-slate-900">
                      <div>{r.memberName}</div>
                      <div className="text-[11px] text-slate-400 font-mono">
                        {r.memberNumber || r.memberId}
                      </div>
                    </td>
                    <td className="py-3.5 px-4 text-slate-700">
                      <span className="font-semibold">{r.paymentType.replace(/_/g, ' ')}</span>
                      {r.loanNumber && (
                        <div className="text-[11px] text-slate-500 font-mono">Loan: {r.loanNumber}</div>
                      )}
                    </td>
                    <td className="py-3.5 px-4">
                      <span className="px-2 py-0.5 rounded bg-slate-100 font-semibold text-slate-700 text-xs">
                        {r.paymentMethod}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 text-right font-bold text-slate-900 text-base">
                      ₱{(r.amountPaid ?? (r as any).amount ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                    </td>
                    <td className="py-3.5 px-4 text-slate-600 text-xs">
                      {new Date(r.paymentDate).toLocaleDateString()}
                    </td>
                    <td className="py-3.5 px-4 text-center">
                      <span
                        className={`inline-block px-2.5 py-0.5 rounded-full text-xs font-bold ${
                          r.status === 'ISSUED'
                            ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                            : 'bg-rose-100 text-rose-800 border border-rose-300'
                        }`}
                      >
                        {r.status}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 text-right">
                      <button
                        onClick={() => setSelectedReceipt(r)}
                        className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-emerald-700 hover:bg-emerald-800 text-white font-semibold text-xs transition shadow-sm"
                      >
                        <Printer className="w-3.5 h-3.5" />
                        <span>View / Print</span>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* SELECTED RECEIPT MODAL */}
      {selectedReceipt && settings && (
        <OfficialReceiptModal
          receipt={selectedReceipt}
          member={members.find(m => m.id === selectedReceipt.memberId || m.memberNumber === selectedReceipt.memberNumber)}
          settings={settings}
          userRole={userRole}
          onClose={() => setSelectedReceipt(null)}
          onRefresh={fetchData}
          onRecordPrint={recordPrint}
          onVoidReceipt={handleVoidReceipt}
        />
      )}

      {/* ISSUE MANUAL RECEIPT MODAL (Staff/Admin) */}
      {showIssueModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/70 p-4 backdrop-blur-sm overflow-y-auto">
          <div className="bg-white rounded-2xl max-w-lg w-full p-6 space-y-4 shadow-2xl border border-slate-200">
            <div className="flex items-center justify-between border-b border-slate-200 pb-3">
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center gap-2">
                <PlusCircle className="w-5 h-5 text-emerald-600" />
                <span>Issue Official Receipt</span>
              </h2>
              <button
                onClick={() => setShowIssueModal(false)}
                className="text-slate-400 hover:text-slate-600 font-bold"
              >
                ×
              </button>
            </div>

            <form onSubmit={handleIssueManualSubmit} className="space-y-3 text-xs sm:text-sm">
              <div>
                <label className="block font-bold text-slate-700 mb-1">Select Member <span className="text-rose-500">*</span></label>
                <select
                  value={manualForm.memberId}
                  onChange={(e) => setManualForm({ ...manualForm, memberId: e.target.value })}
                  className="w-full p-2.5 rounded-xl border border-slate-300 text-xs font-medium focus:ring-2 focus:ring-emerald-500"
                  required
                >
                  <option value="">-- Choose Member --</option>
                  {members.map(m => (
                    <option key={m.id} value={m.id}>
                      {m.fullName} ({m.email})
                    </option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Payment Category <span className="text-rose-500">*</span></label>
                  <select
                    value={manualForm.paymentType}
                    onChange={(e) => setManualForm({ ...manualForm, paymentType: e.target.value as any })}
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs font-medium focus:ring-2 focus:ring-emerald-500"
                  >
                    <option value="SAVINGS_DEPOSIT">Regular Savings Deposit</option>
                    <option value="SHARE_CAPITAL">Share Capital Contribution</option>
                    <option value="LOAN_PAYMENT">Loan Repayment</option>
                    <option value="TIME_DEPOSIT">Time Deposit Placement</option>
                    <option value="FEE">Membership Fee</option>
                    <option value="OTHER">Other Payment</option>
                  </select>
                </div>

                <div>
                  <label className="block font-bold text-slate-700 mb-1">Payment Method <span className="text-rose-500">*</span></label>
                  <select
                    value={manualForm.paymentMethod}
                    onChange={(e) => setManualForm({ ...manualForm, paymentMethod: e.target.value as any })}
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs font-medium focus:ring-2 focus:ring-emerald-500"
                  >
                    <option value="CASH">Cash Over-the-Counter</option>
                    <option value="GCASH">GCash QR</option>
                    <option value="BANK_TRANSFER">Bank Deposit</option>
                    <option value="CHECK">Check</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Amount Paid (₱) <span className="text-rose-500">*</span></label>
                  <input
                    type="number"
                    step="0.01"
                    min="1"
                    value={manualForm.amountPaid}
                    onChange={(e) => setManualForm({ ...manualForm, amountPaid: e.target.value })}
                    placeholder="e.g. 5000.00"
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs font-bold text-slate-900 focus:ring-2 focus:ring-emerald-500"
                    required
                  />
                </div>

                <div>
                  <label className="block font-bold text-slate-700 mb-1">Payment Date</label>
                  <input
                    type="date"
                    value={manualForm.paymentDate}
                    onChange={(e) => setManualForm({ ...manualForm, paymentDate: e.target.value })}
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs focus:ring-2 focus:ring-emerald-500"
                  />
                </div>
              </div>

              {manualForm.paymentType === 'LOAN_PAYMENT' && (
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Associated Loan (Optional)</label>
                  <select
                    value={manualForm.loanId}
                    onChange={(e) => setManualForm({ ...manualForm, loanId: e.target.value })}
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs focus:ring-2 focus:ring-emerald-500"
                  >
                    <option value="">-- Select Active Loan --</option>
                    {loans
                      .filter(l => !manualForm.memberId || l.memberId === manualForm.memberId)
                      .map(l => (
                        <option key={l.id} value={l.id}>
                          {l.loanTypeName} - Bal: ₱{(l.balance ?? 0).toLocaleString()}
                        </option>
                      ))}
                  </select>
                </div>
              )}

              <div>
                <label className="block font-bold text-slate-700 mb-1">Payment Reference / Transaction Ref</label>
                <input
                  type="text"
                  value={manualForm.paymentReference}
                  onChange={(e) => setManualForm({ ...manualForm, paymentReference: e.target.value })}
                  placeholder="e.g. CS-987654 or Bank Deposit Ref"
                  className="w-full p-2.5 rounded-xl border border-slate-300 text-xs focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div>
                <label className="block font-bold text-slate-700 mb-1">Remarks / Particulars</label>
                <textarea
                  value={manualForm.remarks}
                  onChange={(e) => setManualForm({ ...manualForm, remarks: e.target.value })}
                  rows={2}
                  placeholder="Additional notes to print on the receipt..."
                  className="w-full p-2.5 rounded-xl border border-slate-300 text-xs focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-200">
                <button
                  type="button"
                  onClick={() => setShowIssueModal(false)}
                  disabled={isSubmittingManual}
                  className="px-4 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmittingManual}
                  className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-sm"
                >
                  {isSubmittingManual ? 'Generating OR...' : 'Issue & Generate OR'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* RECEIPT CONFIGURATION & TEMPLATE SETTINGS MODAL (Admin Only) */}
      {showSettingsModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/70 p-4 backdrop-blur-sm overflow-y-auto">
          <div className="bg-white rounded-2xl max-w-2xl w-full p-6 space-y-4 shadow-2xl border border-slate-200 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-slate-200 pb-3">
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center gap-2">
                <Settings className="w-5 h-5 text-emerald-600" />
                <span>Official Receipt Branding & Sequence Settings</span>
              </h2>
              <button
                onClick={() => setShowSettingsModal(false)}
                className="text-slate-400 hover:text-slate-600 font-bold"
              >
                ×
              </button>
            </div>

            <form onSubmit={handleSaveSettings} className="space-y-4 text-xs sm:text-sm">
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-3">
                <h3 className="font-bold text-slate-800 text-xs uppercase tracking-wider">
                  OR Numbering Sequence
                </h3>
                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Prefix</label>
                    <input
                      type="text"
                      value={settingsForm.orPrefix}
                      onChange={(e) => setSettingsForm({ ...settingsForm, orPrefix: e.target.value })}
                      className="w-full p-2 rounded-lg border border-slate-300 font-mono text-xs"
                      placeholder="OR-"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Next Counter</label>
                    <input
                      type="number"
                      value={settingsForm.orNextNumber}
                      onChange={(e) => setSettingsForm({ ...settingsForm, orNextNumber: Number(e.target.value) })}
                      className="w-full p-2 rounded-lg border border-slate-300 font-mono text-xs"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Number Padding</label>
                    <input
                      type="number"
                      min="4"
                      max="10"
                      value={settingsForm.numberPadding}
                      onChange={(e) => setSettingsForm({ ...settingsForm, numberPadding: Number(e.target.value) })}
                      className="w-full p-2 rounded-lg border border-slate-300 font-mono text-xs"
                    />
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                <h3 className="font-bold text-slate-800 text-xs uppercase tracking-wider">
                  Cooperative Branding & Header Information
                </h3>

                <div>
                  <label className="block font-bold text-slate-700 mb-1">Cooperative Name Header</label>
                  <input
                    type="text"
                    value={settingsForm.headerTitle}
                    onChange={(e) => setSettingsForm({ ...settingsForm, headerTitle: e.target.value })}
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                    required
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block font-bold text-slate-700 mb-1">CDA Registration No.</label>
                    <input
                      type="text"
                      value={settingsForm.cdaRegNo}
                      onChange={(e) => setSettingsForm({ ...settingsForm, cdaRegNo: e.target.value })}
                      className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                    />
                  </div>
                  <div>
                    <label className="block font-bold text-slate-700 mb-1">Tax Identification No. (TIN)</label>
                    <input
                      type="text"
                      value={settingsForm.tin}
                      onChange={(e) => setSettingsForm({ ...settingsForm, tin: e.target.value })}
                      className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                    />
                  </div>
                </div>

                <div>
                  <label className="block font-bold text-slate-700 mb-1">Official Address</label>
                  <input
                    type="text"
                    value={settingsForm.address}
                    onChange={(e) => setSettingsForm({ ...settingsForm, address: e.target.value })}
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block font-bold text-slate-700 mb-1">Contact Phone</label>
                    <input
                      type="text"
                      value={settingsForm.contactPhone}
                      onChange={(e) => setSettingsForm({ ...settingsForm, contactPhone: e.target.value })}
                      className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                    />
                  </div>
                  <div>
                    <label className="block font-bold text-slate-700 mb-1">Contact Email</label>
                    <input
                      type="email"
                      value={settingsForm.contactEmail}
                      onChange={(e) => setSettingsForm({ ...settingsForm, contactEmail: e.target.value })}
                      className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                    />
                  </div>
                </div>

                <div>
                  <label className="block font-bold text-slate-700 mb-1">Cooperative Logo URL</label>
                  <input
                    type="text"
                    value={settingsForm.logoUrl || ''}
                    onChange={(e) => setSettingsForm({ ...settingsForm, logoUrl: e.target.value })}
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                    placeholder="https://..."
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block font-bold text-slate-700 mb-1">Authorized Signatory Name</label>
                    <input
                      type="text"
                      value={settingsForm.authorizedSignatoryName}
                      onChange={(e) => setSettingsForm({ ...settingsForm, authorizedSignatoryName: e.target.value })}
                      className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                    />
                  </div>
                  <div>
                    <label className="block font-bold text-slate-700 mb-1">Signatory Official Title</label>
                    <input
                      type="text"
                      value={settingsForm.authorizedSignatoryTitle}
                      onChange={(e) => setSettingsForm({ ...settingsForm, authorizedSignatoryTitle: e.target.value })}
                      className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                    />
                  </div>
                </div>

                <div>
                  <label className="block font-bold text-slate-700 mb-1">Footer Note on Receipts</label>
                  <input
                    type="text"
                    value={settingsForm.footerNote}
                    onChange={(e) => setSettingsForm({ ...settingsForm, footerNote: e.target.value })}
                    className="w-full p-2.5 rounded-xl border border-slate-300 text-xs"
                  />
                </div>
              </div>

              <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-200">
                <button
                  type="button"
                  onClick={() => setShowSettingsModal(false)}
                  disabled={isSavingSettings}
                  className="px-4 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSavingSettings}
                  className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-sm"
                >
                  {isSavingSettings ? 'Saving...' : 'Save Settings'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* PRINT AUDIT LOGS MODAL (Admin Only) */}
      {showLogsModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/70 p-4 backdrop-blur-sm overflow-y-auto">
          <div className="bg-white rounded-2xl max-w-3xl w-full p-6 space-y-4 shadow-2xl border border-slate-200 max-h-[85vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-slate-200 pb-3">
              <h2 className="text-lg font-extrabold text-slate-900 flex items-center gap-2">
                <History className="w-5 h-5 text-emerald-600" />
                <span>Global Receipt Print & Download Audit History</span>
              </h2>
              <button
                onClick={() => setShowLogsModal(false)}
                className="text-slate-400 hover:text-slate-600 font-bold"
              >
                ×
              </button>
            </div>

            {printLogs.length === 0 ? (
              <p className="text-center text-xs text-slate-500 py-8">
                No print or download events recorded yet.
              </p>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className="bg-slate-100 text-slate-700 uppercase font-semibold">
                    <tr>
                      <th className="p-2.5">Receipt #</th>
                      <th className="p-2.5">Member</th>
                      <th className="p-2.5">Action</th>
                      <th className="p-2.5">Triggered By</th>
                      <th className="p-2.5">Timestamp</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200">
                    {printLogs.map((log, idx) => (
                      <tr key={idx} className="hover:bg-slate-50">
                        <td className="p-2.5 font-mono font-bold">{log.receiptNumber}</td>
                        <td className="p-2.5">{log.memberName}</td>
                        <td className="p-2.5">
                          <span className="px-2 py-0.5 rounded bg-emerald-50 text-emerald-600 font-semibold text-[11px]">
                            {log.action}
                          </span>
                        </td>
                        <td className="p-2.5">{log.printedBy} ({log.userRole})</td>
                        <td className="p-2.5 text-slate-500 font-mono text-[11px]">
                          {new Date(log.printedAt).toLocaleString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}

    </div>
  );
};
